---- Create users
--INSERT INTO users (id, name, email, password, role) VALUES
--  (1, 'Sai', 'sai@example.com', '1234', 'MENTOR'),
--  (2, 'Chaitu', 'chaitu@example.com', 'abcd', 'MENTOR'),
--  (3, 'Ravi', 'ravi@example.com', 'pass', 'LEARNER'),
--  (4, 'Anu', 'anu@example.com', 'anu123', 'BOTH'),
--  (5, 'Priya', 'priya@example.com', 'priya456', 'MENTOR');
--
---- Create Skills
--INSERT INTO skill (skill_id, skill_name, description, mentor_id) VALUES
--  (101, 'Java', 'Complete Java programming from basics to advanced', 1),
--  (102, 'React', 'Frontend development with React and hooks', 2),
--  (103, 'Data Structures', 'DSA for tech interviews and CP', 1),
--  (104, 'Spring Boot', 'Build REST APIs with Spring Boot', 4),
--  (105, 'SQL', 'Mastering SQL queries and joins', 5);
--
--
--
